### ISSUE TITLE
Long Running polling operation fails with expired token error.

### ISSUE THREAD

**Issue by vincentdass63** [Azure/ms-rest-azure-js#134]
**Package Version**: 2.1.0
- [ ] **browser**
    - **name/version**:  Edge, Chrome
**Describe the bug**

**To Reproduce**
1.  Long running polling operation for more than one hour fails with error stating the access token is expired.
Since the access token expiry value is 1 hour, there should be a mechanism to pass a renew token when faced with 401 response code.

**Additional context**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @vincentdass63 

Can you share a code snippet that we can use to replicate the problem?

**Comment by jeremymeng** [comment]
@vincentdass63 just a friendly ping...a project that demonstrates the issue would be very helpful!

**Comment by ramya-rao-a** [comment]
We usually wait for 2 weeks to hear back before closing the issue. Looks like we more than 3 months over. Closing this issue.
