### ISSUE TITLE
What is 'token' in this case?

### ISSUE THREAD

**Issue by mrbobpowell** [Azure/ms-rest-azure-js#4]
Admittedly I'm new to Azure, but I've covered a lot of docs, and I don't know what 'token' is meant to apply to here. Especially in an environment that has many IDs of various types. An example  would be handy.

**Comment by mrbobpowell** [comment]
So I applied 'mediaservices' as a token, and I get an error when running:
   node samples/node-sample.js
that it can't find ../lib/msRestAzure
   but if I run it from samples I get an error because it's trying to run from samples/samples.

Pretty lame that it can't find one of it's own libraries unless I modify a path.

**Comment by amarzavery** [comment]
@mrbobpowell - Thanks for pointing out the error. I have updated the sample to refer to the correct folder to reference ms-rest-azure.
Mr. Bob, the token refers to the access-token. It is received from Azure once you are authenticated.

The sample code does show steps on how to get the token over [here](https://github.com/Azure/ms-rest-azure-js/blob/master/samples/node-sample.js#L21).

However, I would like to know what is it that you are trying to achieve? What is your end to end scenario?
